# Generated by Django 4.1.2 on 2022-10-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
